# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sniffle Workshop
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for the workshop site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rethinkmlpapers
github_username:  rethinkmlpapers

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- index.md
- speakers.md
- organizers.md
- callforpapers.md
- schedule.md
- papers.md
- contactus.md

# # Specify the name of a file to show as a masthead graphic at the top of each page, instead of a title, here:
# masthead: assets/img/banner.jpg
# # Description (alt text) for the masthead
# masthead_description: Adapted from Machine Learning & Artificial Intelligence by mikemacmarketing; licensed under CC BY 2.0

# A two-line attribution (remove this if you have to, but we'd appreciate if you leave this as is)
attribution: >
  Based on a <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> template from a <a href="https://krrish94.github.io">lazy grad student</a>.
  Some icons made by <a href="https://smashicons.com/" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>.

# Displays a "last updated" date in the footer if set to "true"
last_updated: true

# Define collections (speakers, organizers, papers)
# To turn off any of these collections, just set "output" to "false"
collections:
  speakers:
    output: true
  organizers:
    output: true
  schedule:
    sort_by: sequence_id
    output: true
  papers:
    sort_by: sequence_id
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Google analytics id. Add your tracking id to get visitor stats.
# google_analytics: # tracking id
